qiniu/rs.js

putPolicy add fsizeMin

---

qiniu/rs.js

HTTPS supported for private space.

Make secure base url

---

qiniu/rs.js

addCallbackBodyType

---

qiniu/io.js
test/io.test.js

增加方法 `putReadable` ，并作为 `put`与`putFile`的基本方法，
```
var rs = fs.createReadStream(imageFile);
qiniu.io.putReadable(uptoken, key, rs, null, function(err, ret) {});
```
为新方法添加了测试用例，并且通过测试

add putReadable, put data from Readable

---

qiniu/rsf.js
test/io.test.js

addDelimiter

---

qiniu/io.js

misspelling

---

qiniu/rs.js

addDeleteAfterDays

---

index.js
qiniu/io.js
qiniu/rs.js

extra.crc32的值没有加入到put form，遗漏了

fix missing crc32 form field

---

qiniu/zone.js

修改解析token中的scope

---

qiniu/rs.js

addChangeMime

---

examples/rsDemo.js
qiniu/rs.js
test/rs.test.js

ADD Delete after days

---

test/rs.test.js

Reverts qiniu/nodejs-sdk.v6#224

Revert "fix test"

---

qiniu/storage/form.js

fix crc32 issue

---

qiniu/storage/resume.js

fix an issue  resumeUploader failed  when the last chunk is less than 2056

---

examples/cdn_create_timestamp_antileech_url.js
qiniu/cdn.js

url query 可能不是 键值对的形式，例如： http://sq.qiniuts.com/2.png?imageView2/2/w/480/format/jpg

improve the compatibility of timestamp_antileech

---

qiniu/storage/rs.js

https://developer.qiniu.com/kodo/api/4173/modify-the-file-status
resolve: https://github.com/qiniu/nodejs-sdk/issues/298

Add changeStatusOp

---

examples/pfops_video_plus.js

add example of video pulp

---

qiniu/storage/rs.js

add bucket operations and change file status function

bucket operations

---

examples/form_upload_simple.js
qiniu/fop.js
qiniu/storage/form.js
qiniu/storage/resume.js
qiniu/storage/rs.js

repair upload never use cache and invalid UnixTime compare

invalid cache

---

qiniu/storage/rs.js

fix: add forceSaveKey for policy

---

examples/form_upload_simple.js
examples/resume_upload_simple.js
index.d.ts
qiniu/storage/form.js
qiniu/storage/resume.js
test/form_up.test.js
test/resume_up.test.js

1. fix #389
2. use CdnUpHost to improve tests success rate
[内部工单 KODO-14232](https://jira.qiniu.io/browse/KODO-14232)

fix upload lost metadata & use CdnUpHost to improve tests success rate

---

index.d.ts
qiniu/conf.js
qiniu/rpc.js
qiniu/storage/rs.js
qiniu/zone.js
test/fop.test.js
test/form_up.test.js
test/resume_up.test.js
test/rs.test.js

- support deep archive
- fix fetching zone
- fix some CI issues
[内部工单 KODO-14592](https://jira.qiniu.io/browse/KODO-14592)
[内部工单 KODO-14721](https://jira.qiniu.io/browse/KODO-14721)

Support deep archive & Fix fetching zone

---

examples/object_lifecycle.js
index.d.ts
qiniu/storage/rs.js
test/cdn.test.js
test/fop.test.js
test/rs.test.js

[内部工单 KODO-14806](https://jira.qiniu.io/browse/KODO-14806)

support object lifecycle

---

index.d.ts
package.json
qiniu/auth/digest.js
qiniu/rpc.js
qiniu/storage/rs.js
qiniu/util.js
test/rs.test.js
test/util.test.js

[内部工单 KODO-15076](https://jira.qiniu.io/browse/KODO-15076)

add X-Qiniu-Date and fix bucket lifecycle tests

---

examples/form_qvm_upload.js
qiniu/conf.js
qiniu/zone.js

[内部工单 KODO-15248](https://jira.qiniu.io/browse/KODO-15248)

remove deprecate domains

---

qiniu/zone.js

[内部工单 KODO-15348](https://jira.qiniu.io/browse/KODO-15348)

add Zones cn-east-2, ap-seoul-1

---

qiniu/conf.js
qiniu/rpc.js
qiniu/zone.js
test/util.test.js

reorder query region hosts and retore basic request methods

---

qiniu/storage/rs.js
qiniu/util.js
test/util.test.js

fix batch rs host
